/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.eeep.gui;

import com.eeep.controle.AluguelControle;
import com.eeep.controle.FilmeControle;
import com.eeep.model.Aluguel;
import com.eeep.model.Filme;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Junior
 */
public class BuscarAluguel extends javax.swing.JFrame {

    /**
     * Creates new form BuscarAluguel
     */
    public BuscarAluguel() {
        initComponents();
        listar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        campoBusca = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaResultado = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("Buscar");

        campoBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoBuscaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoBuscaKeyReleased(evt);
            }
        });

        tabelaResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pessoa", "Filme", "Data aluguel", "Data devolução"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaResultado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
                    .addComponent(campoBusca, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoBuscaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoBuscaKeyPressed
        // TODO add your handling code here:

        
    }//GEN-LAST:event_campoBuscaKeyPressed

    private void campoBuscaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoBuscaKeyReleased
        // TODO add your handling code here:
        DefaultTableModel model = null;
        AluguelControle controle = new AluguelControle();

        ArrayList<Aluguel> alugueis = controle.buscar(campoBusca.getText());
        model = (DefaultTableModel) tabelaResultado.getModel();
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }
        for (Aluguel aluguel : alugueis) {
            Date dataAluguel = aluguel.getDataAluguel();
            Date dataDevolucao = aluguel.getDataDevolucao();
            String diaA;
            String mesA;
            String anoA;
            if(dataAluguel.getDate()<10){
                diaA = "0"+dataAluguel.getDate();
            }else{
                diaA = ""+dataAluguel.getDate();
            }
            if(dataAluguel.getMonth()<9){
                mesA = "0"+(dataAluguel.getMonth()+1);
            }else{
                mesA = ""+(dataAluguel.getMonth()+1);
            }
            anoA = ""+(dataAluguel.getYear()+1900);
            String aluguelFormatado = diaA+"/"+mesA+"/"+anoA;
            
            String diaD;
            String mesD;
            String anoD;
            if(dataDevolucao.getDate()<10){
                diaD = "0"+dataDevolucao.getDate();
            }else{
                diaD = ""+dataDevolucao.getDate();
            }
            if(dataDevolucao.getMonth()<9){
                mesD = "0"+(dataDevolucao.getMonth()+1);
            }else{
                mesD = ""+(dataDevolucao.getMonth()+1);
            }
            anoD = ""+(dataDevolucao.getYear()+1900);
            String devolucaoFormatado = diaD+"/"+mesD+"/"+anoD;
 
            model.addRow(new Object[]{
                aluguel.getPessoa().getNome(), aluguel.getFilme().getNome(),
                aluguelFormatado, devolucaoFormatado
            });
        }
    }//GEN-LAST:event_campoBuscaKeyReleased

    public void listar() {
        DefaultTableModel model = null;
        AluguelControle controle = new AluguelControle();
        ArrayList<Aluguel> alugueis = controle.listar();
        model = (DefaultTableModel) tabelaResultado.getModel();
        for (Aluguel aluguel : alugueis) {
            Date dataAluguel = aluguel.getDataAluguel();
            Date dataDevolucao = aluguel.getDataDevolucao();
            String diaA;
            String mesA;
            String anoA;
            if(dataAluguel.getDate()<10){
                diaA = "0"+dataAluguel.getDate();
            }else{
                diaA = ""+dataAluguel.getDate();
            }
            if(dataAluguel.getMonth()<9){
                mesA = "0"+(dataAluguel.getMonth()+1);
            }else{
                mesA = ""+(dataAluguel.getMonth()+1);
            }
            anoA = ""+(dataAluguel.getYear()+1900);
            String aluguelFormatado = diaA+"/"+mesA+"/"+anoA;
            
            String diaD;
            String mesD;
            String anoD;
            if(dataDevolucao.getDate()<10){
                diaD = "0"+dataDevolucao.getDate();
            }else{
                diaD = ""+dataDevolucao.getDate();
            }
            if(dataDevolucao.getMonth()<9){
                mesD = "0"+(dataDevolucao.getMonth()+1);
            }else{
                mesD = ""+(dataDevolucao.getMonth()+1);
            }
            anoD = ""+(dataDevolucao.getYear()+1900);
            String devolucaoFormatado = diaD+"/"+mesD+"/"+anoD;
 
            model.addRow(new Object[]{
                aluguel.getPessoa().getNome(), aluguel.getFilme().getNome(),
                aluguelFormatado, devolucaoFormatado
            });
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarAluguel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarAluguel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarAluguel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarAluguel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarAluguel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoBusca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaResultado;
    // End of variables declaration//GEN-END:variables

}
